version: '3.8'

services:
  library-management-system:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 15131622
      MYSQL_DATABASE: librarydb
      MYSQL_USER: carlos
      MYSQL_PASSWORD: 15131622
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

